version: "3.5"
networks:
  app-net:
volumes:
  app-data:


services:
  # ------------------------
  # Nginx - php-fpm versions
  # ------------------------

  # debug nginx: docker run -d <image-name> "nginx-debug" "-g" "daemon off;"
  nginx:
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile
    networks:
      - app-net
    ports:
      - "8099:80"
    volumes:
      - ./public:/srv/app/public

  php:
    build:
      args:
        - PHP_VERSION=${PHP_VERSION}
      context: .
      dockerfile: .docker/php/Dockerfile
    networks:
      - app-net
#    depends_on:
#      - mariadb
    ports:
      - "9003:9003"
    volumes:
      - .:/srv/app
    env_file: .env

  # ------------------------
  # Databases
  # ------------------------
#  mariadb:
#    image: mariadb:10.5
#    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
#    ports:
#      - "13306:3306"
#    environment:
#      - MYSQL_DATABASE=demo
#      - MYSQL_ROOT_PASSWORD=password
#    networks:
#      - app-net
#    env_file: .env

  smtp:
    image: mailhog/mailhog
    ports:
      - 8025:8025
